export const screenName = {
  loading: "Loading",
  sign_in: "SignIn",
  sign_up: "SignUp",
  phone_verification: "PhoneNumberVerification",
  otp_verification: "OtpVerification",
  reset_password: "Reset Password",
  new_password: "New Password",
  bottom_tab_navigator: "BottomTabNavigator",
  tabBarName: {
    home: "Home",
    categories: "Categories",
    businesses: "Businesses",
    my_shopping: "MyShopping",
    profile: "Profile",
  },
  home_stack: "HomeStackNavigator",
  categories_details: "CategoriesDetails",
  item_list: "ItemList",
  item_details: "ItemDetails",
  filter: "Filter",
  seller_profile: "SellerProfile",
  add_review: "AddReview",
  search: "Search",
  edit_profile: "EditProfile",
  my_address: "MyAddress",
  new_address: "NewAddress",
  checkout_add_address: "CheckoutAddAddress",
  checkout_payment: "CheckoutPayment",
  checkout_order_review: "CheckoutOrderReview",
  order_success: "OrderSuccess",
  my_orders: "MyOrders",
  my_favorite: "MyFavorite",
  map_location: "MapLocation",
  order_details: "OrderDetails",
  guest_checkout: "GuestCheckout",
  all_view_item: "AllViewItem",
  my_cards: "MyCards",
  notification: "Notification",
};

export const fontFamily = {
  // bold: "ReadexPro-Bold",
  bold: "ReadexPro-SemiBold",
  light: "ReadexPro-Light",
  medium: "ReadexPro-Medium",
  regular: "ReadexPro-Regular",
  semiBold: "ReadexPro-SemiBold",
  extraLight: "ReadexPro-ExtraLight",
};
